### ISSUE TITLE
Errors when executing

### ISSUE THREAD

**Issue by jpollino** [fud0/itEbooksDownloader#1]
Downloading ebook with id 1: ERROR OCCURRED!
Downloading ebook with id 2: ERROR OCCURRED!
Downloading ebook with id 3: ERROR OCCURRED!
Downloading ebook with id 4: ERROR OCCURRED!
Downloading ebook with id 5: ERROR OCCURRED!
Downloading ebook with id 6: ERROR OCCURRED!
Downloading ebook with id 7: ERROR OCCURRED!
Downloading ebook with id 8: ERROR OCCURRED!
Oct 15, 2013 3:38:42 PM net.htmlparser.jericho.LoggerProviderJava$JavaLogger info
INFO: StartTag a at (r131,c17,p7062) has missing whitespace after quoted attribute value at position (r131,c74,p7119)
Oct 15, 2013 3:38:42 PM net.htmlparser.jericho.LoggerProviderJava$JavaLogger info
INFO: StartTag a at (r131,c17,p7062) has missing whitespace after quoted attribute value at position (r131,c76,p7121)
Oct 15, 2013 3:38:42 PM net.htmlparser.jericho.LoggerProviderJava$JavaLogger info
INFO: StartTag a at (r131,c17,p7062) contains attribute name with invalid character at position (r131,c84,p7129)
Oct 15, 2013 3:38:42 PM net.htmlparser.jericho.LoggerProviderJava$JavaLogger info
INFO: StartTag a at (r131,c17,p7062) has missing whitespace after quoted attribute value at position (r131,c86,p7131)
Oct 15, 2013 3:38:42 PM net.htmlparser.jericho.LoggerProviderJava$JavaLogger info
INFO: StartTag img at (r131,c103,p7148) has missing whitespace after quoted attribute value at position (r131,c207,p7252)
Oct 15, 2013 3:38:42 PM net.htmlparser.jericho.LoggerProviderJava$JavaLogger info
INFO: StartTag img at (r131,c103,p7148) has missing whitespace after quoted attribute value at position (r131,c209,p7254)
Oct 15, 2013 3:38:42 PM net.htmlparser.jericho.LoggerProviderJava$JavaLogger info
INFO: StartTag img at (r131,c103,p7148) contains attribute name with invalid character at position (r131,c217,p7262)
Oct 15, 2013 3:38:42 PM net.htmlparser.jericho.LoggerProviderJava$JavaLogger info
INFO: StartTag img at (r131,c103,p7148) has missing whitespace after quoted attribute value at position (r131,c219,p7264)
Oct 15, 2013 3:38:42 PM net.htmlparser.jericho.LoggerProviderJava$JavaLogger info
INFO: StartTag a at (r132,c6,p7306) has missing whitespace after quoted attribute value at position (r132,c63,p7363)
Oct 15, 2013 3:38:42 PM net.htmlparser.jericho.LoggerProviderJava$JavaLogger info
INFO: StartTag a at (r132,c6,p7306) has missing whitespace after quoted attribute value at position (r132,c65,p7365)
Oct 15, 2013 3:38:42 PM net.htmlparser.jericho.LoggerProviderJava$JavaLogger info
INFO: StartTag a at (r132,c6,p7306) contains attribute name with invalid character at position (r132,c73,p7373)
Oct 15, 2013 3:38:42 PM net.htmlparser.jericho.LoggerProviderJava$JavaLogger info
INFO: StartTag a at (r132,c6,p7306) has missing whitespace after quoted attribute value at position (r132,c75,p7375)

is anyone still working on this script?

**Comment by fud0** [comment]
Hi, 
I will try to figure out if I can spend some hours in order to give a look to the problems and maybe fix them, plus implementing the additional features I was thinking about.

Anyhow I'm quite busy at the moment, and I'm not sure if I will have the chance to work on it sooner in the next few days.

Best regards,
Massimo.

**Comment by fud0** [comment]
I've checked-in a fix for the problem. There were changes in how the files could be downloaded. Created a new tag for 0.2 version. You can checkout the updated working jar.
