### ISSUE TITLE
hi! download stops at certain limit..

### ISSUE THREAD

**Issue by vlasvlasvlas** [fud0/itEbooksDownloader#3]
Hi! love this script!!

but download stops after 100 pdfs (more o less), so i dunno if its a limitation from it-ebooks site or something about the script.

thanks!! :)

**Comment by fud0** [comment]
Hi, 
it could be related to some kind of limitation from the website itself or the hoster. Something more advanced would require to add proxy configuration or similar.
I planned to rewrite the program, maybe adding a simple UI to be more similar to other download tools.
Unfortunately I still had not the time to start working on it.
I Will probably do in the next upcoming weeks.
Stay tuned!

Regards,
Massimo.

**Comment by vlasvlasvlas** [comment]
txs!!
